//Page de Pacientes
package proyectosia;


/**
 *
 * @author novoy
 */
public class PageP extends javax.swing.JPanel {
    private Datos datos; // <- atributo de Datos

    public PageP(Datos datos) {
        this.datos = datos; // <- guardar referencia
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(846, 397));
        setMinimumSize(new java.awt.Dimension(846, 397));
        setPreferredSize(new java.awt.Dimension(846, 397));

        jLabel1.setText("FUNCIONES PARA ADMINISTRAR PACIENTES");

        jButton1.setText("Agregar Nuevo Paciente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Mostrar Listado de Pacientes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Mostrar Sesiones Terapéuticas de un Paciente");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Registrar Sesión Terapéutica de un Paciente");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Cambiar Estado de un Paciente");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(301, 306, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(300, 300, 300))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
    String rut = javax.swing.JOptionPane.showInputDialog(this, "Ingrese Rut del Nuevo Paciente:");
    if (rut == null || rut.trim().isEmpty()) return;

    // Validar si ya existe
    boolean existe = datos.pacientes.stream()
            .anyMatch(p -> p.getRut().equalsIgnoreCase(rut.trim()));

    if (existe) {
        javax.swing.JOptionPane.showMessageDialog(this, "Paciente ya registrado con ese RUT.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    String nombre = javax.swing.JOptionPane.showInputDialog(this, "Ingrese Nombre del Nuevo Paciente:");
    if (nombre == null || nombre.trim().isEmpty()) return;

    String edadStr = javax.swing.JOptionPane.showInputDialog(this, "Ingrese Edad del Nuevo Paciente:");
    if (edadStr == null || edadStr.trim().isEmpty()) return;

    int edad;
    try {
        edad = Integer.parseInt(edadStr.trim());
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Edad inválida.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    String fechaNacimiento = javax.swing.JOptionPane.showInputDialog(this, "Ingrese Fecha de Nacimiento (ej: 01-01-2000):");
    if (fechaNacimiento == null || fechaNacimiento.trim().isEmpty()) return;

    // Crear paciente y agregar a la lista
    Paciente nuevo = new Paciente(rut.trim(), nombre.trim(), edad, fechaNacimiento.trim());
    datos.pacientes.add(nuevo);

    // Guardar cambios
    datos.guardarPacientes();

    javax.swing.JOptionPane.showMessageDialog(this, "Paciente agregado correctamente.");
    }

                                       

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if (datos.pacientes.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "NO EXISTEN PACIENTES REGISTRADOS", "Listado Pacientes", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        StringBuilder listado = new StringBuilder();
        int i = 0;
        for (Paciente pTemp : datos.pacientes) {
            listado.append("#####################\n");
            listado.append("Datos Paciente n°").append(i + 1).append("\n");
            listado.append("#####################\n");
            listado.append("Nombre del Paciente: ").append(pTemp.getNombre()).append("\n");
            listado.append("Rut del Paciente: ").append(pTemp.getRut()).append("\n");
            listado.append("Edad del Paciente: ").append(pTemp.getEdad()).append("\n");
            listado.append("Fecha de Nacimiento: ").append(pTemp.getFechaDeNacimiento()).append("\n");
            listado.append("Estado: ").append(pTemp.getEstado() ? "TERMINÓ terapia" : "NO ha terminado terapia").append("\n");
            listado.append("-----------------------------\n");
            i++;
        }

        // Crear JTextArea para mostrar el listado
        javax.swing.JTextArea textArea = new javax.swing.JTextArea(listado.toString());
        textArea.setEditable(false);
        textArea.setColumns(40);
        textArea.setRows(20);
        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);

        // Mostrar en ventana
        javax.swing.JOptionPane.showMessageDialog(this, scrollPane, "Listado de Pacientes", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration                   
}